"""Step 3a: export a checkpoint as a self-contained `solution/` folder the eval grader can run.

The grader mounts solution/ read-only with solve.py's directory on sys.path, inside a container
that has robobench + torch but not this package or rsl_rl. So the folder carries everything:
    solve.py     the generic entry point (template below): rebuild obs -> policy -> env.step
    policy.pt    TorchScript of (obs normalizer -> actor MLP), deterministic mean action
    rl_obs.py    a copy of robobench_rl/obs.py (torch-only) so the observation rule is identical
    env.json     obs config + layout, action bounds, control rate, episode length (from training)
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import torch
import yaml

SOLVE_TEMPLATE = '''"""RL policy solution — generated by rl/robobench_rl/export.py; nothing here is task-specific.

solve(env): rebuild the training observation rule on the graded env, run the TorchScript actor
deterministically at the training control rate for the training episode length (or until the
scene's own success() holds), mapping [-1, 1] actions onto the controller's action bounds.
"""
import json
from pathlib import Path

import torch

import rl_obs  # sibling copy of the training observation rule

HERE = Path(__file__).resolve().parent
META = json.loads((HERE / "env.json").read_text())


def solve(env) -> None:
    dev = env.device
    o = META["obs"]
    obs_fn = rl_obs.StateObs(env, drop_keys=tuple(o.get("drop_keys", ())), env_local=o.get("env_local", True),
                             ee_pose=o.get("ee_pose", True), last_action=o.get("last_action", True))
    if obs_fn.dim != META["num_obs"]:
        raise RuntimeError(f"obs dim {obs_fn.dim} != trained {META['num_obs']}: layout {obs_fn.layout}")
    policy = torch.jit.load(str(HERE / "policy.pt"), map_location=str(dev)).eval()
    lo = torch.tensor(META["action_lo"], device=dev)
    hi = torch.tensor(META["action_hi"], device=dev)
    n, A = env.num_envs, META["num_actions"]
    last = torch.zeros(n, A, device=dev)
    success = getattr(env.scene, "success", None)
    with torch.no_grad():
        for _ in range(int(META["max_episode_length"])):
            obs = obs_fn.compute(last)
            a = policy(obs).clamp(-1.0, 1.0)
            env.step(lo + (a + 1.0) * 0.5 * (hi - lo))
            last = a
            if callable(success):
                ok = success()
                if bool(torch.as_tensor(ok).all()):
                    break
'''


class _Actor(torch.nn.Module):
    def __init__(self, normalizer: torch.nn.Module, actor: torch.nn.Module) -> None:
        super().__init__()
        self.normalizer, self.actor = normalizer, actor

    def forward(self, obs: torch.Tensor) -> torch.Tensor:
        return self.actor(self.normalizer(obs))


def load_actor_critic(run_dir: Path, checkpoint: Path):
    """Rebuild rsl_rl's ActorCritic from the run's config + a checkpoint (no env needed)."""
    from tensordict import TensorDict
    from rsl_rl.modules import ActorCritic

    meta = json.loads((run_dir / "env.json").read_text())
    ppo = meta["ppo"]
    pol = dict(ppo["policy"])
    pol.pop("class_name", None)
    n_obs = int(meta["num_obs"])
    obs = TensorDict({"policy": torch.zeros(1, n_obs), "critic": torch.zeros(1, n_obs)}, batch_size=[1])
    ac = ActorCritic(obs, ppo["obs_groups"], int(meta["num_actions"]), **pol)
    ckpt = torch.load(checkpoint, map_location="cpu", weights_only=False)
    ac.load_state_dict(ckpt["model_state_dict"])
    ac.eval()
    return ac, meta, ckpt


def export_solution(run_dir: str | Path, checkpoint: str | Path, out_dir: str | Path) -> Path:
    run_dir, checkpoint, out_dir = Path(run_dir), Path(checkpoint), Path(out_dir)
    ac, meta, ckpt = load_actor_critic(run_dir, checkpoint)
    out_dir.mkdir(parents=True, exist_ok=True)
    actor = _Actor(ac.actor_obs_normalizer, ac.actor).eval()
    example = torch.zeros(1, int(meta["num_obs"]))
    with torch.no_grad():
        scripted = torch.jit.trace(actor, example)
        # sanity: traced == eager on random input
        x = torch.randn(4, int(meta["num_obs"]))
        if not torch.allclose(scripted(x), actor(x), atol=1e-5):
            raise RuntimeError("traced actor disagrees with eager actor")
    scripted.save(str(out_dir / "policy.pt"))
    shutil.copy(Path(__file__).with_name("obs.py"), out_dir / "rl_obs.py")
    (out_dir / "solve.py").write_text(SOLVE_TEMPLATE)
    meta_out = {k: meta[k] for k in ("preset", "num_obs", "num_actions", "step_dt", "max_episode_length",
                                     "obs_layout", "obs", "action_lo", "action_hi")}
    meta_out["checkpoint"] = checkpoint.name
    meta_out["train_iteration"] = int(ckpt.get("iter", -1))
    meta_out["run_dir"] = str(run_dir)
    (out_dir / "env.json").write_text(json.dumps(meta_out, indent=2))
    if (run_dir / "config.yaml").exists():
        shutil.copy(run_dir / "config.yaml", out_dir / "train_config.yaml")
    return out_dir
