"""Export a checkpoint as a self-contained `solution/` folder the eval grader can run.

The grader mounts solution/ read-only with solve.py's directory on sys.path, in a container with
robobench + torch but not this package or rsl_rl. So the folder carries: solve.py (generic loop), policy.pt
(TorchScript actor + obs normalizer, deterministic), rl_obs.py (a copy of the observation rule) and
env.json (action map, obs config, finger PD, horizon) — everything needed to replay the training pipeline."""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import torch

SOLVE_TEMPLATE = '''"""RL policy solution — generated by rl/robobench_rl/export.py; nothing here is task-specific."""
import json
from pathlib import Path

import torch

import rl_obs  # sibling copy of the training observation rule

HERE = Path(__file__).resolve().parent
META = json.loads((HERE / "env.json").read_text())


def map_action(env, a, m, dev):
    E, mirror = int(m["env_action_dim"]), list(m.get("mirror_dims") or [])
    if mirror:
        keep = [d for d in range(E) if d not in mirror]
        full = torch.zeros(a.shape[0], E, device=dev)
        full[:, keep] = a[:, : len(keep)]
        full[:, mirror] = a[:, -1:].expand(-1, len(mirror))
        a = full
    lo, hi = torch.tensor(m["lo"], device=dev), torch.tensor(m["hi"], device=dev)
    out = lo + (a + 1.0) * 0.5 * (hi - lo)
    if m.get("jd_dims"):
        q = env.robot.articulation.data.joint_pos[:, m["jd_joint_ids"]]
        lim = torch.tensor(m["jd_lim"], device=dev)
        out = out.clone()
        out[:, m["jd_dims"]] = (q + a[:, m["jd_dims"]] * float(m["jd_scale"])).clamp(lim[:, 0], lim[:, 1])
    return out


def solve(env) -> None:
    dev = env.device
    kp = META.get("gripper_stiffness")
    if kp:  # the finger PD the policy was trained with (the scripted solvers set theirs the same way)
        art = env.robot.articulation
        art.write_joint_stiffness_to_sim(float(kp), joint_ids=art.find_joints(list(env.robot.GRIPPER_JOINTS))[0])
    o = META["obs"]
    obs_fn = rl_obs.StateObs(env, drop_keys=tuple(o.get("drop_keys", ())), env_local=o.get("env_local", True),
                             ee_pose=o.get("ee_pose", True), last_action=o.get("last_action", True),
                             action_dim=META["num_actions"])
    if obs_fn.dim != META["num_obs"]:
        raise RuntimeError(f"obs dim {obs_fn.dim} != trained {META['num_obs']}")
    policy = torch.jit.load(str(HERE / "policy.pt"), map_location=str(dev)).eval()
    last = torch.zeros(env.num_envs, META["num_actions"], device=dev)
    with torch.no_grad():
        for _ in range(int(META["max_episode_length"])):
            a = policy(obs_fn.compute(last)).clamp(-1.0, 1.0)
            env.step(map_action(env, a, META["action_map"], dev))
            last = a
'''


class _Actor(torch.nn.Module):
    def __init__(self, normalizer, actor) -> None:
        super().__init__()
        self.normalizer, self.actor = normalizer, actor

    def forward(self, obs):
        return self.actor(self.normalizer(obs))


def export_solution(run_dir: str | Path, checkpoint: str | Path, out_dir: str | Path) -> Path:
    from tensordict import TensorDict
    from rsl_rl.modules import ActorCritic

    run_dir, checkpoint, out_dir = Path(run_dir), Path(checkpoint), Path(out_dir)
    meta = json.loads((run_dir / "env.json").read_text())
    ckpt = torch.load(checkpoint, map_location="cpu", weights_only=False)
    sd = ckpt["model_state_dict"]
    n_obs = int(sd[next(k for k in sd if k.startswith("actor.") and k.endswith("weight"))].shape[1])
    pol = dict(meta["ppo"]["policy"])
    pol.pop("class_name", None)
    obs = TensorDict({"policy": torch.zeros(1, n_obs), "critic": torch.zeros(1, n_obs)}, batch_size=[1])
    ac = ActorCritic(obs, meta["ppo"]["obs_groups"], int(meta["num_actions"]), **pol)
    ac.load_state_dict(sd)
    ac.eval()
    out_dir.mkdir(parents=True, exist_ok=True)
    actor = _Actor(ac.actor_obs_normalizer, ac.actor).eval()
    with torch.no_grad():
        scripted = torch.jit.trace(actor, torch.zeros(1, n_obs))
        x = torch.randn(4, n_obs)
        if not torch.allclose(scripted(x), actor(x), atol=1e-5):
            raise RuntimeError("traced actor disagrees with eager actor")
    scripted.save(str(out_dir / "policy.pt"))
    shutil.copy(Path(__file__).with_name("obs.py"), out_dir / "rl_obs.py")
    (out_dir / "solve.py").write_text(SOLVE_TEMPLATE)
    meta_out = {k: meta[k] for k in ("preset", "num_actions", "step_dt", "max_episode_length", "obs", "action_map",
                                     "gripper_stiffness")}
    meta_out.update(num_obs=n_obs, checkpoint=checkpoint.name, train_iteration=int(ckpt.get("iter", -1)), run_dir=str(run_dir))
    (out_dir / "env.json").write_text(json.dumps(meta_out, indent=2))
    if (run_dir / "config.yaml").exists():
        shutil.copy(run_dir / "config.yaml", out_dir / "train_config.yaml")
    return out_dir
