"""Datagen campaigns on RunPod: one disposable RTX 4090 pod per task, detached.

The pod runs orchestrate + the Claude Code agent + Isaac on its own GPU (the eval
harness's substrate: the same secure-cloud pod, the same Isaac environment snapshot
restored from the EU-RO-1 network volume — eval/scripts/run_agent_runpod.py owns
create/provision/ssh and is imported here, not copied). Nothing depends on the
laptop after launch: the pod mirrors its campaign to the network volume every
lap, stops ITSELF when the orchestrator exits (done, INCOMPLETE, crash, or the
model route dead for 30 min -> exit 75), and a relaunch under the same
--gen-name resumes from the mirror.

    python data_engine/scripts/runpod_dgen_campaign.py launch \\
        --tasks coffee,spatula [--model model_hub/robo_orange_o50] [--gen-name gen_o50_v1]
    python data_engine/scripts/runpod_dgen_campaign.py status      # every dgen-* pod
    python data_engine/scripts/runpod_dgen_campaign.py stop        # terminate every dgen-* pod

Inputs: /tmp/dgen_inputs/stage/<task>/{run.json,workspace/...} (eval-run-shaped).
Mirror: <network volume>/dgen_out/<task>/data_gen/<gen name>/ (+ orchestrate.log, exit).
PhysX tasks only: the snapshot carries the PhysX Isaac venv, not the Newton build.
"""

from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve()
REPO_ROOT = HERE.parents[2]
sys.path.insert(0, str(REPO_ROOT / "eval" / "scripts"))
import run_agent_runpod as rp  # noqa: E402  (the RunPod substrate: keys, pods, ssh, snapshot)

INPUTS = Path("/tmp/dgen_inputs/stage")
POD_REPO = "/repo"
POD_WORK = "/work"
MIRROR = f"{rp.SNAPSHOT_MOUNT}/dgen_out"          # the network volume, shared by every pod
NODE_PATH = "/opt/node-v22.11.0-linux-x64/bin:/opt/npm/bin"
SSH_KEY = str(Path.home() / ".ssh" / "cosigen_campaign")

RUNNER = r"""#!/bin/bash
# datagen pod runner (generated by runpod_dgen_campaign.py) — resume, mirror, run, stop.
TASK={task}; GEN={gen}; OUT={mirror}/$TASK; WORK={work}/$TASK; POD_ID={pod_id}
echo $$ > /root/dgen_run.pid   # kill THIS first when restarting the orchestrator by hand, or the
                              # exit path below mirrors and terminates the pod
export PATH={node_path}:$PATH
export OMNI_KIT_ACCEPT_EULA=YES ACCEPT_EULA=Y PRIVACY_CONSENT=Y OMNI_KIT_ALLOW_ROOT=1
export OMNI_KIT_CRASH_REPORTER=0 CARB_CRASHREPORTER_ENABLED=0 NVIDIA_DRIVER_CAPABILITIES=all
export DGEN_AGENT_MODEL={model} DGEN_CODE_HASH={code_hash} DGEN_MIRROR_TASK_DIR=$OUT
mkdir -p $OUT $WORK/data_gen
if [ -d $OUT/data_gen/$GEN ]; then
  echo "[dgen $TASK] resuming from mirrored campaign state"
  cp -a $OUT/data_gen/. $WORK/data_gen/
fi
MIRROR="{venv}/bin/python {repo}/data_engine/scripts/mirror.py $WORK $OUT"
( while true; do sleep 180; $MIRROR; done ) > $WORK/mirror.log 2>&1 &
MIRROR_PID=$!
{venv}/bin/python {repo}/data_engine/scripts/orchestrate.py $WORK \
  --isaac-py {venv}/bin/python \
  --agent-cmd "python3 {repo}/data_engine/scripts/claude_agent_loop.py --model {model}" \
  {flags} > $WORK/orchestrate.log 2>&1
RC=$?
kill $MIRROR_PID 2>/dev/null
$MIRROR
echo "rc=$RC $(date -u +%FT%TZ)" > $OUT/exit.txt
echo "[dgen $TASK] orchestrate exited $RC — mirrored; terminating pod $POD_ID"
# the pod id is a LITERAL from the launcher (the env var was unset in this nohup'd shell
# and the DELETE went to /pods/ — 8 pods idled 6-13 h); the response is logged, not dropped
curl -sS -o /root/terminate_response.txt -w "terminate HTTP %{{http_code}}\n" -X DELETE \
  -H "Authorization: Bearer {runpod_key}" https://rest.runpod.io/v1/pods/$POD_ID
"""

RENDER_RUNNER = r"""#!/bin/bash
# render worker {k}/{n} (generated by runpod_dgen_campaign.py): copy the campaign from the
# mirror, render this worker's share, push frames only, stop.
TASK={task}; OUT={mirror}/$TASK; WORK={work}/$TASK; POD_ID={pod_id}
export OMNI_KIT_ACCEPT_EULA=YES ACCEPT_EULA=Y PRIVACY_CONSENT=Y OMNI_KIT_ALLOW_ROOT=1
export OMNI_KIT_CRASH_REPORTER=0 CARB_CRASHREPORTER_ENABLED=0 NVIDIA_DRIVER_CAPABILITIES=all
export DGEN_CODE_HASH={code_hash}
mkdir -p $WORK && cp -a $OUT/. $WORK/
PUSH="{venv}/bin/python {repo}/data_engine/scripts/mirror.py --renders-only $WORK $OUT"
( while true; do sleep 180; $PUSH; done ) > $WORK/mirror.log 2>&1 &
PUSH_PID=$!
{venv}/bin/python {repo}/data_engine/scripts/orchestrate.py $WORK \
  --isaac-py {venv}/bin/python {flags} --render-worker {k}/{n} > $WORK/render_worker_{k}.log 2>&1
RC=$?
kill $PUSH_PID 2>/dev/null
$PUSH
cp -f $WORK/render_worker_{k}.log $OUT/render_worker_{k}.log
echo "[render {task} {k}/{n}] exited $RC — pushed; terminating pod $POD_ID"
curl -sS -o /root/terminate_response.txt -w "terminate HTTP %{{http_code}}\n" -X DELETE \
  -H "Authorization: Bearer {runpod_key}" https://rest.runpod.io/v1/pods/$POD_ID
"""


def flags_for(a: argparse.Namespace) -> str:
    """The orchestrator's spec flags — identical to the Modal launcher's."""
    f = {"--physics-target": a.physics_target,
         "--visual-draws": a.visual_draws, "--num-envs": a.num_envs,
         "--stage-hours": a.stage_hours, "--sessions": a.sessions,
         "--job-concurrency": a.job_concurrency, "--render-envs": a.render_envs,
         "--intervention-session-min": a.session_min, "--name": a.gen_name}
    flags = " ".join(f"{k} {shlex.quote(str(v))}" for k, v in f.items())
    return flags + (f" {a.orchestrate_extra}" if a.orchestrate_extra else "")


def code_hash() -> str:
    sha = subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
                         capture_output=True, text=True).stdout.strip() or "nogit"
    dirty = subprocess.run(["git", "-C", str(REPO_ROOT), "status", "--porcelain",
                            "data_engine", "robobench"], capture_output=True, text=True).stdout
    return f"runpod-{sha}{'-dirty' if dirty.strip() else ''}"


def launch_one(task: str, a: argparse.Namespace, ssh_pub: str, worker: tuple[int, int] | None = None) -> rp.Pod:
    """One campaign pod for `task`, or (worker=(k, n)) one render worker for it."""
    src = INPUTS / task
    if worker is None:
        if not (src / "run.json").is_file():
            raise SystemExit(f"no staged input for {task} at {src}")
        status = json.loads((src / "run.json").read_text()).get("source_status")
        if status != "completed" and not a.allow_unverified_seed:
            # a seed from a run that never solved the task costs the whole pre-check clock
            # (tool_packing: 12 h, 5 repair sessions, PRECHECK_FAILED)
            raise SystemExit(f"{task}: seed run ended '{status}', not 'completed' — pass "
                             "--allow-unverified-seed to launch it anyway")
    name = f"dgen-{task}" if worker is None else f"dgen-render-{task}-{worker[0]}"
    pod = rp.create_pod(name, ssh_pub, SSH_KEY, gpu_count=1)
    try:
        rp.provision_pod(pod)                     # the Isaac snapshot (venv incl. imageio,
                                                  # pyyaml), node, claude
        for rel in ("robobench", "data_engine"):
            rp.upload_dir(pod, REPO_ROOT / rel, f"{POD_REPO}/{rel}")
        if worker is None:
            rp.upload_dir(pod, src, f"{POD_WORK}/{task}")
        subprocess.run(["scp", "-i", SSH_KEY, "-P", str(pod.port),
                        "-o", "StrictHostKeyChecking=accept-new",
                        str(REPO_ROOT / "pyproject.toml"), f"root@{pod.ip}:{POD_REPO}/pyproject.toml"],
                       check=True, capture_output=True)
        if worker is None:
            runner = RUNNER.format(task=task, gen=a.gen_name, mirror=MIRROR, work=POD_WORK,
                                   node_path=NODE_PATH, model=a.model, code_hash=code_hash(),
                                   venv=rp.VENV, repo=POD_REPO, flags=flags_for(a),
                                   runpod_key=rp.RUNPOD_KEY, pod_id=pod.id)
        else:
            runner = RENDER_RUNNER.format(task=task, mirror=MIRROR, work=POD_WORK, code_hash=code_hash(),
                                          venv=rp.VENV, repo=POD_REPO, flags=flags_for(a),
                                          runpod_key=rp.RUNPOD_KEY, pod_id=pod.id,
                                          k=worker[0], n=worker[1])
        rp.sh(pod, f"cat > /root/dgen_run.sh <<'RUNNER_EOF'\n{runner}\nRUNNER_EOF\n"
                   f"chmod +x /root/dgen_run.sh && rm -rf {POD_REPO}/data_engine/tests", quiet=True)
        rp.sh(pod, "nohup /root/dgen_run.sh > /root/dgen_run.log 2>&1 &", quiet=True)
        # Wait for the runner to reach the orchestrator: on a resume it first copies the
        # campaign back from the network volume, which takes minutes for a large mirror (a
        # fixed 5 s check once declared two healthy resumes dead and terminated their pods).
        # Fail only if the runner process itself is gone. `pgrep` patterns are anchored: an
        # unanchored `pgrep -f orchestrate.py` matches the probing shell's own command line.
        orch = f"^{rp.VENV}/bin/python {POD_REPO}/data_engine/scripts/orchestrate.py"
        deadline = time.time() + 60 * 60
        while True:
            rc, out = rp.sh(pod, f"pgrep -f '{orch}' >/dev/null && echo RUNNING; "
                                 "kill -0 $(cat /root/dgen_run.pid 2>/dev/null) 2>/dev/null && echo RUNNER_ALIVE; "
                                 "tail -2 /root/dgen_run.log", quiet=True)
            if "RUNNING" in out:
                break
            if "RUNNER_ALIVE" not in out or time.time() > deadline:
                raise SystemExit(f"orchestrate did not start on {pod.id}:\n{out}")
            time.sleep(10)
        print(f"[dgen {task}{'' if worker is None else f' render {worker[0]}/{worker[1]}'}] running on pod "
              f"{pod.id} ({pod.ip}:{pod.port})", flush=True)
        return pod
    except BaseException:
        rp.terminate_pod(pod)
        raise


def dgen_pods() -> list[dict]:
    return [p for p in rp.rest("GET", "/pods").get("items", [])
            if str(p.get("name", "")).startswith("dgen-")]


def status(gen_name: str) -> None:
    pods = dgen_pods()
    print(f"{len(pods)} dgen pods")
    for p in pods:
        task = p["name"].removeprefix("dgen-")
        ip, port = p.get("publicIp"), (p.get("portMappings") or {}).get("22")
        line = f"{task:15s} pod {p['id']} {p.get('desiredStatus', '?'):8s}"
        if ip and port:
            pod = rp.Pod(id=p["id"], ip=ip, port=int(port), ssh_key=SSH_KEY)
            _, out = rp.sh(pod, f"cat {POD_WORK}/{task}/data_gen/{gen_name}/status.json 2>/dev/null; "
                                f"tail -1 {POD_WORK}/{task}/orchestrate.log 2>/dev/null",
                           quiet=True, timeout=60)
            line += "  " + " ".join(out.split())[:220]
        print(line, flush=True)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("action", choices=["launch", "status", "stop", "render-workers"])
    ap.add_argument("--workers", type=int, default=4,
                    help="render-workers: extra pods rendering the campaign's manifest in parallel")
    ap.add_argument("--tasks", default="", help="comma-separated PhysX tasks")
    ap.add_argument("--model", default="model_hub/robo_orange_o50")
    ap.add_argument("--gen-name", default="gen_o50_v1")
    ap.add_argument("--physics-target", type=int, default=200)
    ap.add_argument("--visual-draws", type=int, default=3)
    ap.add_argument("--num-envs", type=int, default=512)
    ap.add_argument("--stage-hours", type=float, default=12.0, help="hard cap of every gate")
    ap.add_argument("--allow-unverified-seed", action="store_true",
                    help="launch even if the seed run's source_status is not 'completed'")
    ap.add_argument("--sessions", default="scene,strategy,phase")
    ap.add_argument("--job-concurrency", type=int, default=1)
    ap.add_argument("--render-envs", type=int, default=16)
    ap.add_argument("--session-min", type=float, default=120.0)
    ap.add_argument("--orchestrate-extra", default="",
                    help="extra orchestrate.py flags verbatim (e.g. reduced targets for a smoke run)")
    a = ap.parse_args()

    if a.action == "status":
        status(a.gen_name)
        return
    if a.action == "stop":
        for p in dgen_pods():
            rp.terminate_pod(rp.Pod(id=p["id"], ip="", port=0, ssh_key=SSH_KEY))
        return
    tasks = [t for t in a.tasks.split(",") if t]
    if not tasks:
        raise SystemExit(f"{a.action} needs --tasks")
    ssh_pub = Path(SSH_KEY + ".pub").read_text().strip()
    if a.action == "render-workers":
        # N pods per task, each rendering a deterministic share of the manifest from the
        # mirror and pushing frames back; the campaign's own pod (or a resume) picks them up
        from concurrent.futures import ThreadPoolExecutor
        jobs = [(t, k) for t in tasks for k in range(a.workers)]
        with ThreadPoolExecutor(max_workers=len(jobs)) as ex:
            list(ex.map(lambda tk: launch_one(tk[0], a, ssh_pub, worker=(tk[1], a.workers)), jobs))
        print(f"launched {len(jobs)} render workers", flush=True)
        return
    up = {p["name"].removeprefix("dgen-") for p in dgen_pods()}
    todo = [t for t in tasks if t not in up]
    if up & set(tasks):
        print(f"already running, skipped: {sorted(up & set(tasks))}", flush=True)

    def launch(task: str) -> bool:
        for attempt in (1, 2):   # a pod that never becomes reachable costs one retry, not the wave
            try:
                launch_one(task, a, ssh_pub)
                return True
            except SystemExit as exc:
                print(f"[dgen {task}] launch attempt {attempt} failed: {exc}", flush=True)
        return False

    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=len(todo) or 1) as ex:   # launches are independent
        results = dict(zip(todo, ex.map(launch, todo)))
    failed = [t for t, ok in results.items() if not ok]
    print(f"launched {len(todo) - len(failed)} pods; they mirror to {MIRROR} and stop "
          f"themselves" + (f"; FAILED to launch: {failed}" if failed else ""), flush=True)


if __name__ == "__main__":
    main()
